services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    command: sh -c "npx prisma generate --schema=src/prisma/schema.prisma && npm run dev"
